
name: Node.js Package
on: push

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: ''
      - run: yarn set version stable
      - run: yarn install
      - run: yarn jest
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: ''
      - name: configure yarn
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          echo -en "\"npmAuthToken\": \"$REGISTRY_TOKEN\"\n\"npmPublishRegistry\": \"https://registry.npmjs.org\"" >> ~/.yarnrc.yml
      - name: upgrade yarn
        run: yarn set version stable
      - run: yarn plugin import workspace-tools
      - run: yarn workspaces focus --production
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - run: yarn workspaces foreach --exclude kafka-lib npm publish --access public
